# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: DotNet_Build

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v3
      with:
        name: dotnet-published-output  # Give the artifact a name
        path: output                   # Path to the output directory
        retention-days: 60             # Number of Days to retain the artifact.
    - name: List workspace files
      run: ls ${{ github.workspace }}/output
